### ISSUE TITLE
프로젝트 경로 설정

### ISSUE THREAD

**Issue by kdongha** [SCCPJT/instagram_clone_frontend#9]
../../../ 식의 경로보다
components/atoms/MyCompo 식으로 절대경로가 보기 좋을것 같습니다.
utils, state등도 설정이 필요합니다.

**Comment by kdongha** [comment]
types 도 필요할것 같고 추가적으로 더 필요한게 있을까요
@Dinoryong @HyeonHak @haeunkim428

**Comment by HyeonHak** [comment]
https://ithub.tistory.com/320 참고해서 경로 설정
